name: Deploy

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout g-api
      uses: actions/checkout@v3
    
    - name: Use Node.js 21
      uses: actions/setup-node@v3
      with:
        node-version: 21
        
    - name: Install redocly
      run: npm install -g @redocly/cli@latest

    - name: Redocly lint
      run: redocly lint ./*.yaml --config ./configs/lint.yaml

  trigger-g-core:
    needs: lint
    runs-on: ubuntu-latest
    steps:
    - name: Fire event
      run: |
        curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.ACCESS_TOKEN }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/umu-art/g-core/actions/workflows/deploy.yml/dispatches \
          -d '{"ref":"master", "inputs":{}}'
